#!/usr/bin/python3
# Реализация Бинарного поиска

def binary_search(list, item):
    ''' В переменных low и high хранятся границы
    той части списка, в которой выполняется
    поиск '''
    low = 0
    high = len(list) -1

    while low <= high:      # Пока эта часть не сократится до одного элемента ...
        mid = (low + high) // 2  # ... проверяем средний элемент
        guess = list[mid]
        if guess == item:  # Значение найдено
            return mid
        if guess > item:  # Много
            high = mid - 1
        else:  # Мало
            low = mid + 1
    return None  # Значение не существует

my_list = [1, 3, 5, 7, 9]  # А теперь протестируем функцию!

print(binary_search(my_list, 9))  #=> 1 Вспомните: нумерация элементов начинается с 0.
print( binary_search(my_list, 1) )  #=> None
